### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by sem-geologist** [hyperspy/rosettasciio#108]
Could the github discussion tab be enabled for this repository? Some stuff are for discussions, and could take place out from issues.

**Comment by ericpre** [comment]
I have enabled it to try.

**Comment by ericpre** [comment]
Shall we convert the suitable issues to discussions?

**Comment by sem-geologist** [comment]
I saw it sometimes are practiced in some of repositories and goes in both ways. The good thing is that it does not blow the issues so they stay on short and on topic. Thanks I will initiate some stuff in discussions.
