### ISSUE TITLE
pip / conda install for rosettascio?

### ISSUE THREAD

**Issue by cophus** [hyperspy/rosettasciio#12]
What is the planned roadmap for adding a pip / conda install to rosettascio?  We could then do some testing using it as a reader for many file formats which py4DSTEM does not currently support.

Thanks for spinning this off as a separate library!

**Comment by ericpre** [comment]
I would say possibly about a month. In the mean time it can be installed with:
```
pip install https://github.com/hyperspy/rosettasciio/archive/refs/heads/main.zip
```

It would be great if you could start using it and provide feedback on the usage.

**Comment by jlaehne** [comment]
Coming soon, everything prepared in #126 and #129. See also #99
