### ISSUE TITLE
Ragged Array Reading is Slow(er than it should be)

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/rosettasciio#168]
#### Describe the bug
There appears to be a bug somewhere in `zarr` (and I would imagine `h5py` based on the fact that the loading speed is similar) with regards to loading ragged arrays.

#### To Reproduce
```python
data = np.array([np.random.randint(0, 100, size=np.random.randint(0, 20)).astype(np.float64)
                  for i in range(i)], dtype=object)
s = hs.signals.BaseSignal(data)
s.save("data.zspy", overwrite=True)
%prun hs.load("data.zspy")
```

#### Expected behavior

Ideally some chunk would be compressed once and then loaded once on each save/load cycle.  What is actually happening is different for `.zspy` and `.hspy`.

For `.hspy` each index in the ragged array is compressed individually and then uncompressed individually.  This isn't efficient at all but isn't the worst case scenario. 

For `.zspy` multiple indexes in the ragged array are compressed at one time but it seems like only 1 index is being uncompressed at a time.  The result is that as you increase the number of indexes compressed (n) the time to uncompress is multiplied by (n).

#### Python environement:
 - RosettaSciIO version: 0.0.2dec
 - Python version: 3.9

#### Additional context
See #164 for more context

**Comment by ericpre** [comment]
Done in https://github.com/hyperspy/rosettasciio/pull/169.
