### ISSUE TITLE
set_log_level for rosettasciio is needed

### ISSUE THREAD

**Issue by nem1234** [hyperspy/rosettasciio#69]
#### Describe the functionality you would like to see.
Like hyperspy's  hs.set_log_level function, rosettasciio.set_log_level is needed.
May be hs.set_log_level should also control rsciio.set_log_level.

**Comment by ericpre** [comment]
> Like hyperspy's hs.set_log_level function, rosettasciio.set_log_level is needed.

Yes, indeed it would be convenient to have something similiar.

> May be hs.set_log_level should also control rsciio.set_log_level.

In principle, it should stay separated.

**Comment by nem1234** [comment]
> In principle, it should stay separated.
I agree it, but, currently no warning messages are shown while loading files from hyperspy.
Setting default logging level of WARNING seems useful.
