### ISSUE TITLE
Folder/submodule naming

### ISSUE THREAD

**Issue by jlaehne** [hyperspy/rosettasciio#78]
Currently, the folder naming for plugins does not follow the plugin naming in the `specifications.yml` files. As the submodules are named according to the folder names one would for example load `from rsciio.prz import file_reader`, while the documented plugin-name (e.g. used for the HyperSpy `reader` argument) is `PantaRhei`. The `prz` as import-name is not documented anywhere in the docs. I would therefore propose to make the folder name and format name consistent for all plugins to avoid confusion.

Currently the following plugins have deviating folder names (ignoring partial capitalization in plugin names):
```
plugin name        | folder name        -> proposed folder name
------------------------------------------------------
BrukerComposite    | bruker             -> brukercomposite
DigitalMicrograph  | digital_micrograph -> digitalmicrograph   (alternatively renaming to DM to shorten everything?)
TIA                | fei                -> tia
JobinYvon          | jobin_yvon         -> jobinyvon
PantaRhei          | prz                -> pantarhei
Semper             | semper_unf         -> semper
DigitalSurfSurface | sur                -> digitalsurf  (making DigitalSurfSurface alias name)
USID               | usid_hdf           -> usid
```

I would though tend to keep the capitalization in the plugin names as it is clear that module names should be lowercase (the `reader` argument in HyperSpy is insensitive to capitalization), but an alternative could be to also change all plugin names to lowercase to be fully consistent?

(I would though wait with the implementation until #76 is finished and merged to avoid a conflict.)

**Comment by ericpre** [comment]
This sounds good. The only thing that I am unsure is with bruker, as the reader can also read `spx` file, not only `bcf`.
