### ISSUE TITLE
Automatically make PR's for `black`

### ISSUE THREAD

**Issue by CSSFrancis** [hyperspy/rosettasciio#95]
#### Describe the functionality you would like to see.
In pyxem we recently added in a Github action which automatically pushes a PR when the code base doesn't follow the most recent `black` specification. (https://github.com/pyxem/pyxem/pull/914) The idea is that if someone merges some code without applying `black` we can easily remedy that by merging in the auto created PR.  (See here for what those look like https://github.com/pyxem/pyxem/pull/915)  

Is this something that would be helpful here?

#### Describe the context
There are a couple of reasons for this addition.  Mainly it helps when new contributors who aren't familiar with `black` try to add code.  While eventually you want people to be running `black` locally there are cases where merging the code and then just merging the automatically contributed PR is easier than trying to get someone to run black just to get the code working.

It also will create PR's when new versions of `black` are released helping to keep on top of those changes.

**Comment by ericpre** [comment]
There is a workflow to check if the code change are not formatted properly and considering running `black .` is not too painful, I think that it would be a bit redundant. We should be careful with suing third party action accessing the `secrets.GITHUB_TOKEN` as this increase the risk of security issue. At the same time, the `peter-evans/create-pull-request` action is widely used, so it is possibly not that much of an issue.

**Comment by CSSFrancis** [comment]
> There is a workflow to check if the code change are not formatted properly and considering running `black .` is not too painful, I think that it would be a bit redundant. 

Admittedly my opinion of `black` is colored by my first use of it.  I got a little frustrated by the changes from successive version to version.  I mistook "uncompromising" to also mean "unchanging" and it took me a little while to understand why some code was failing the CI when it passed on my computer.  We can shelve this idea for now and maybe resurrect it if there are PR's which appear to be stuck before merging based on not applying `black`.

It might also be good to make sure that at the beginning of each new year the new version of `black` is tested so that the first PR of the year doesn't come with additional formatting changes. 

>We should be careful with suing third party action accessing the `secrets.GITHUB_TOKEN` as this increase the risk of security issue. At the same time, the `peter-evans/create-pull-request` action is widely used, so it is possibly not that much of an issue.

Fair enough.  I believe the appropriate thing to do is create a fork of the repo.  That should help reduce the security issues.
